### ISSUE TITLE
Timestamp Skew response

### ISSUE THREAD

**Issue by StarpTech** [hueniverse/scarecrow#7]
Does scarecrow supports the `timestamp skew` response? When I use an invalid timestamp I only get a response like that without tm and tsm values.

Response:
`
{"statusCode":401,"error":"Unauthorized","message":"Error: Stale timestamp"}
`

ResponseHeaders: 
`
content-type: application/json; charset=utf-8
cache-control: no-cache
`

The Boom object is correct but hapi 8.5.3 send no headers.

**Comment by StarpTech** [comment]
I found the issue on line https://github.com/hueniverse/scarecrow/blob/master/lib/index.js#L86 you don't pass the boom object from hawk.

**Comment by hueniverse** [comment]
Should just pass along the error as-is. Same as here:
https://github.com/hapijs/hapi-auth-hawk/blob/master/lib/index.js#L57-L60

I'll take a PR.

**Comment by StarpTech** [comment]
Thanks!
